[package]
name = "tozz-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
warp = "0.3"
sha2 = "0.9"
hex = "0.4"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }